base_url = "https://notturno.net"
title = "Notturno"
description = "Digital Garden & Portfolio"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
author = "maku"
default_language = "it"
taxonomies = [{ name = "tags", feed = true }]
#date_format = "%d %B %Y" # Formato: 15 Febbraio 2026


[search]
# index_format = "elasticlunr_json"
index_format = "fuse_json"



[extra]
accent_color = "#ff7800"
accent_color_dark = "#ffa348"
emoji_favicon = "ðŸŒƒ"
show_copy_button = true
show_reading_time = true
show_share_button = true
show_backlinks = true
csp = [
	{ directive = "font-src", domains = ["'self'"] },
	{ directive = "img-src", domains = ["'self'", "https:", "data:"] },
	{ directive = "media-src", domains = ["'self'", "https:"] },
	{ directive = "script-src", domains = ["'self'"] },
	{ directive = "style-src", domains = ["'self'", "'unsafe-inline'"] },
	{ directive = "frame-src", domains = ["https://player.vimeo.com", "https://www.youtube-nocookie.com", "https://toot.community"] },
	{ directive = "connect-src", domains = ["https://toot.community"] },
	{ directive = "base-uri", domains = ["'none'"] },
	{ directive = "form-action", domains = ["'none'"] }
]


[extra.nav]
show_feed = true
show_theme_switcher = true
links = [
    { url = "@/journal/_index.md", name = "Journal" }
]

#[extra.footer]
#links = [
#	{ url = "@/privacy-policy/index.md", name = "Privacy Policy" },
#	{ url = "@/cookie-policy/index.md", name = "Cookie Policy" },
#	{ url = "@/atom.xml", name = "RSS" }
#]
#socials = [
#    { url = "https://bsky.app/profile/notturno.net", name = "Bluesky"  }
#]









## Lingua principale
#
#
## Parametri Feed (Sintassi Zola 0.19.x)
#
#
#
## Tema
#
#
#
## --- SLUGIFY ---
## Forza la coerenza tra i nomi file e gli URL (WordPress Style)
#[slugify]
#paths = "on"
#taxonomies = "on"
#
## --- TASSONOMIE ---
## Necessarie per gestire Tag e Categorie nel Front Matter
##taxonomies = [
##    { name = "tags", feed = true },
##    { name = "categories", feed = true },
##]
#
## --- MARKDOWN ---
#[markdown]
##highlighting = true
#render_emoji = true
## Evita che la build fallisca per link non ancora risolti dalla pipeline
##link_checker.level = "warn"
#
## --- CONFIGURAZIONE ITALIANO (Default) ---

#
## MENU FOOTER (Privacy & Cookie Policy)

#
## --- CONFIGURAZIONE INGLESE (Opzionale/Draft) ---
## [languages.en]
## title = "Notturno (EN)"
## description = "Digital Garden & Portfolio"
## generate_feeds = true
## weight = 1
## [languages.en.extra]
## menu = [
##     { name = "Journal", url = "/en/journal" },
##     { name = "Ideas", url = "/en/idees" },
##     { name = "Projects", url = "/en/projets" },
##     { name = "Links", url = "/en/liens" }
## ]